### ISSUE TITLE
hfinder import error

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hcam_finder#17]
With the new release of astropy v3.0, hfinder does not load...

hfinder
Traceback (most recent call last):
  File "/usr/local/python3_modules/bin/hfinder", line 20, in <module>
    from hcam_finder.config import (load_config, write_config,
  File "/usr/local/lib/python3.5/dist-packages/hcam_finder/__init__.py", line 7, in <module>
    from .hcam_finder import *
  File "/usr/local/lib/python3.5/dist-packages/hcam_finder/hcam_finder.py", line 18, in <module>
    from astropy.vo.client import conesearch
ImportError: No module named 'astropy.vo'

http://docs.astropy.org/en/stable/vo/conesearch/index.html
says "Cone Search has been moved to Astroquery 0.3.5 and will be removed from Astropy in a future version."

changing hcam_finder.py...
from astropy.vo.client import conesearch
to
import astroquery.vo_conesearch

works.

Cheers
Pablo.

**Comment by StuartLittlefair** [comment]
thanks @paulkerry1 

Fixed in https://github.com/HiPERCAM/hcam_finder/commit/7545d87b653d275ef5b0032ac00a6636db5d790f
