### ISSUE TITLE
ufinder problem

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam_finder#32]
* hcam-finder version: 1.2.1
* Python version: 3.10.6
* Operating System: linux/fedora36

Vague idea I have encountered this before, but can't remember how to fix it, so thought it should appear as a possible issue. Hope there is a simple fix; was trying to make a chart for upcoming run:

ufinder
Traceback (most recent call last):
  File "/home/phsaap/.local/bin/ufinder", line 15, in <module>
    from ginga.tkw.ImageViewTk import ImageViewCanvas
  File "/usr/lib/python3.10/site-packages/ginga/tkw/ImageViewTk.py", line 26, in <module>
    from ginga.util.toolbox import ModeIndicator  # noqa
  File "/usr/lib/python3.10/site-packages/ginga/util/toolbox.py", line 16, in <module>
    from astropy.utils.data import _find_pkg_data_path
ImportError: cannot import name '_find_pkg_data_path' from 'astropy.utils.data' (/usr/lib64/python3.10/site-packages/astropy/utils/data.py)

**Comment by trmrsh** [comment]
Alex Brown suggested updating ginga and that did the trick.
