### ISSUE TITLE
hfinder does not display the field

### ISSUE THREAD

**Issue by JaumeOM** [HiPERCAM/hcam_finder#40]
* hcam-finder version: 1.3.2 (up to today)
* Python version: 3.11.4
* Operating System: macOS Mojave 10.14.3

### Description

I launched hfinder and I get some prints related to ginga:
```
/opt/anaconda3/envs/hipercam/bin/hfinder:41: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  OLD_GINGA = LooseVersion(ginga.__version__) <= LooseVersion("2.7.1")
2023-07-24 17:53:04,065 | I | ImageView.py:986 (capture_default_viewer_profile) | captured default profile
2023-07-24 17:53:04,068 | I | ImageViewTk.py:90 (choose_best_renderer) | best renderer available is 'pil'
```
Then, I input a target, click on 'query simbad', the coordinates are displayed, click on 'Load image', and the finding chart window keep in black. It is not displaying the field. And some errors are displayed. However, I can save the finding chart and it shows the field. 

Here you can find the error message:
```
AttributeError: 'ImageDraw' object has no attribute 'textsize'
2023-07-24 17:57:19,727 | E | ImageView.py:1384 (redraw_now) | Error redrawing image: 'ImageDraw' object has no attribute 'textsize'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/ImageView.py", line 1368, in redraw_now
    self.redraw_data(whence=whence)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/ImageView.py", line 1407, in redraw_data
    self.private_canvas.draw(self)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/DrawingMixin.py", line 708, in draw
    super(DrawingMixin, self).draw(viewer)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/CompoundMixin.py", line 126, in draw
    obj.draw(viewer)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/DrawingMixin.py", line 708, in draw
    super(DrawingMixin, self).draw(viewer)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/CompoundMixin.py", line 126, in draw
    obj.draw(viewer)
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/types/astro.py", line 415, in draw
    cx, cy = self.get_textpos(cr, tn, cx1, cy1, cx2, cy2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/canvas/types/astro.py", line 424, in get_textpos
    htwd, htht = cr.text_extents(text)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/pilw/CanvasRenderPil.py", line 98, in text_extents
    return self.cr.text_extents(text, self.font)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/hipercam/lib/python3.11/site-packages/ginga/pilw/PilHelp.py", line 134, in text_extents
    retval = self.ctx.textsize(text, font.font)
             ^^^^^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

I hope I explained the error properly.
Best,
Jaume

**Comment by StuartLittlefair** [comment]
Perfect, thanks @JaumeOM 

This looks like a conflict between the version of pillow you have installed with the version of ginga. 

Can you open a Python interpreter and tell me the results of the following commands:

```python
import ginga 
import PIL

print(f“ginga version = {ginga.__version__}“ )
print(f“pillow version = {PIL.__version__}“ )
```

**Comment by JaumeOM** [comment]
Hi @StuartLittlefair ,
Yes, my installed versions in the environment are:
```
import ginga 
import PIL
print(ginga.__version__)
4.1.0
print(PIL.__version__)
10.0.0
```
Best,
Jaume

**Comment by StuartLittlefair** [comment]
Hi @JaumeOM 

I can confirm that this is a conflict between ginga and the latest version of pillow. 

For now you should be able to fix this with 

`pip uninstall Pillow`
`pip install Pillow==9.5`

I have registered a bug with ginga who will update this in the next release

**Comment by JaumeOM** [comment]
Hi @StuartLittlefair ,
I confirm that the field is now displayed. Thank you!
