### ISSUE TITLE
Can not start up hfinder

### ISSUE THREAD

**Issue by skycattmll** [HiPERCAM/hcam_finder#51]
* hcam-finder version: 1.3.4
* Python version: 3.9
* Operating System: MacOS Sonoma 14.2, Mac pro with M2 chip

### Description

Before on a Mac pro with intel chip the old version 1.1.2 runs perfectly. The whole system was transferred to a new Mac pro with M2 chip.

I updated the hcam_finder version from 1.1.2 to 1.3.4 and I ran `hfinder` then it gives such error messages:

```
Traceback (most recent call last):
  File "/Users/iac/opt/anaconda3/bin/hfinder", line 28, in <module>
    from hcam_widgets.compo import widgets as compo_widgets
  File "/Users/iac/opt/anaconda3/lib/python3.8/site-packages/hcam_widgets/compo/widgets.py", line 16, in <module>
    from .utils import (
  File "/Users/iac/opt/anaconda3/lib/python3.8/site-packages/hcam_widgets/compo/utils.py", line 103, in <module>
    importlib_resources.files("hcam_widgets") / "data" / "compo_lens_offset.csv"
AttributeError: module 'importlib.resources' has no attribute 'files'
```

### What I Did

I uninstalled the latest version and reinstalled the old version but the problem was not solved.

**Comment by StuartLittlefair** [comment]
Hi @skycattmll 

Sorry for the slow response, I was away a lot over Xmas. The underlying issue here is with backwards incompatible changes to the `importlib` module that were introduced in Python 3.9. It might be solved by:

- updating hcam_widgets, or
- tweaks to the code.

So I know which is needed, can you let me know the results of 

```python
import hcam_widgets
hcam_widgets.__version__
```

Thanks!

**Comment by StuartLittlefair** [comment]
It is possible this is also fixed by upgrading the `importlib_resources` library, which is a backport of `importlib` for older Python versions. Can you also let me know if `pip install -U importlib_resources` fixes your issue?

**Comment by skycattmll** [comment]
Hi @StuartLittlefair 

I tried `pip install -U importlib_resources` but the problems continues

the result of `import hcam_widgets 
hcam_widgets.__version__` is 1.1.2

**Comment by StuartLittlefair** [comment]
Apologies @skycattmll 

I haven't forgotten about this! It will require changes to the way we package files within the repository and I'm trying to work out how to do this so it works for all versions of Python

**Comment by StuartLittlefair** [comment]
Hi @skycattmll 

I think I have a version that works with older Python installations now. I'm not sure it will all work as desired (we may have other dependencies that are too old - e.g Ginga), but at least this issue should be addressed.

Can you try pip install hcam_finders==1.3.5 and let me know if you have any success?

**Comment by skycattmll** [comment]
Thank you very much @StuartLittlefair 

now `sudo pip install hcam_finder==1.3.5` solve the problem and can launch the GUI.


I have another question: now seems that hfinder fails to get the PS1 image, saying there is no image at the location but actually there is.

**Comment by StuartLittlefair** [comment]
Odd. It usually works fine for me. Which sky position, and are there any error messages or warnings in the terminal?

**Comment by skycattmll** [comment]
Hi @StuartLittlefair 

this is the error message before...
`2024-01-25 14:05:05,409 | E | finders.py:606 (_load_image) | Failed to download sky image: HTTP Error 404: Not Found
2024-01-25 14:05:07,014 | I | panstarrs.py:110 (search) | Querying catalog: PS1
2024-01-25 14:05:08,840 | E | finders.py:606 (_load_image) | Failed to download sky image: HTTP Error 400: bad request`

But now it works fine after i restart the programme...., maybe i really did something wrong.... this was also the reason that i reinstalled the program, and then encountered the error and then raised the question here hahahaha.

Anyway, thank you for your support again :)
